#!/bin/bash

fig run --rm yads watchmedo shell-command \
    --patterns="*.py;*.html" \
    --recursive \
    --command='REUSE_DB=1 ./manage.py test' \
    --wait \
    --ignore-patterns="*/.*" \
    .
